[package]
name = "nasrinator"
version = "0.1.0"
authors = ["Carson Page <carson.page@byterealm.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
zip = "0.5.1"
custom_error = "1.6.0"
roxmltree = "0.6.0"
quick-xml = "0.13.3"
regex = "1.1.2"
lazy_static = "1.3.0"
itertools = "0.8.0"
